install: true
script:
  - mvn -s .travis-settings.xml -B -fae -P$SERVER_VERSION integration-test

language: java
jdk:
  - oraclejdk8
#  - oraclejdk9
env:
  #- SERVER_VERSION=wildfly1010
  - SERVER_VERSION=wildfly1000
  - SERVER_VERSION=wildfly1100
  #- SERVER_VERSION=wildfly1100,secmgr
#  - SERVER_VERSION=wildfly1110
#  - SERVER_VERSION=wildfly1110,secmgr
#  - SERVER_VERSION=wildfly1200
#  - SERVER_VERSION=wildfly1200,secmgr
matrix:
  exclude:
    - jdk: oraclejdk9
      env: SERVER_VERSION=wildfly1010 SECURITY_MGR=false
    - jdk: oraclejdk9
      env: SERVER_VERSION=wildfly1000 SECURITY_MGR=false
    - jdk: oraclejdk9
      env: SERVER_VERSION=wildfly1110 SECURITY_MGR=false

# Test with wildfly/master while waiting for org.wildlfy:wildfly-dist:zip:*
  include:
      # compile with jdk8 and run tests with jdk9
    - jdk: oraclejdk8
      env: TEST_PROFILE=wildfly1200
      install: travis-scripts/wfly-checkout.sh
      jdk_switcher use oraclejdk9
      script: travis-scripts/jbossws-test.sh $TEST_PROFILE
#    - jdk: oraclejdk9
#       env: TEST_PROFILE=wildfly1200
#       script: travis-scripts/wfly-checkout.sh
#               travis-scripts/jbossws-test.sh $TEST_PROFILE
cache:
 directories:
  - $HOME/.m2
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - "if [ -d \"$JAVA_HOME/jre\" ]; then SEC_LIB=$JAVA_HOME/jre; else SEC_LIB=$JAVA_HOME; fi; sudo unzip -j -o  travis-libs/jce_policy-8.zip *.jar -d $SEC_LIB/lib/security;"
