name: JBossWS-CXF CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest ]
        java: ['11']
        wildfly-version: ['wildfly2600', 'wildfly2700']

    steps:
      - name: Checkout jbossws-cxf
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Checkout wildfly2700
        if: contains(matrix.wildfly-version, 'wildfly2700')
        uses: actions/checkout@v3
        with:
          repository: wildfly/wildfly
          ref: '27.0.0.Alpha3'
          path: './wildfly'
      - name: Build WFLY wildfly2700
        if: contains(matrix.wildfly-version, 'wildfly2700')
        working-directory: ./wildfly
        run: mvn -s ../.m2-settings.xml -DskipTests=true '-Denforcer.skip=true' -Prelease clean install
      - name: Build with Maven Java ${{ matrix.java }} on WildFly ${{ matrix.wildfly-version }}
        run: |
          mvn -s ./.m2-settings.xml -B -V -fae -P${{ matrix.wildfly-version }} verify
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/surefire-reports/*.txt'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: server-logs-${{ matrix.os }}-${{ matrix.java }}-${{ matrix.wildfly-version }}
          path: '**/server.log'